project:
  type: website
  output-dir: docs

website:
  title: "Pepperweed Populations LORP 2018–2024"
  site-url: https://yourusername.github.io/noxious-weeds
  navbar:
    title: "Perennial Pepperweed Mapping"
    logo: inyo_logo.png
    left:
      - href: index.html
        text: "Perennial Pepperweed Mapping"
      - icon: github
        href: https://github.com/inyo-gov/noxious-weeds
    background: dark
    search: true
format:
  html:
    theme: bootstrap
    linkcolor: "#2E86AB"
    css: styles.css
    toc: false
    code-fold: true
    code-tools: true
    fig-responsive: true
    table-responsive: false
    fig-dir: figure-html
    subtitle: "Inyo County, California"
    footer: "© 2025 Inyo County, California. All rights reserved."
